services:
  api:
    build: .
    container_name: enterprise-knowledge-assistant-api
    env_file:
      - .env
    volumes:
      - ./data:/service/data

  frontend:
    build:
      context: ./frontend
    container_name: enterprise-knowledge-assistant-frontend
    ports:
      - "80:80"
    depends_on:
      - api